package com.nicsi.store.common.rules;

public enum MakerCheckerOperation {
    OPENING_BALANCE,
    STOCK_ADJUSTMENT,
    BACKDATED_RECEIPT,
    BACKDATED_ISSUE,
    REVERSAL,
    ASSET_CUSTODY_OVERRIDE,
    CONDEMNATION,
    DISPOSAL,
    INVENTORY_VALUE_CORRECTION,
    GRN_POST,
    ASSET_WRITE_OFF,
    REQUISITION_APPROVE,
    TECHNICAL_INSPECTION
}
